___
# Ciência dos Dados - PROJETO 1

Luciana Cocito Alves de Freitas

Segurança Alimentar

___
## Introdução

Descreva aqui o que pretende analisar!

Capriche no português!! 
Se quiser pode utilizar pesquisas semelhantes publicadas em sites confiáveis!!

___
## Análise e Resultados

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [5]:
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\lucia\OneDrive\Documentos\GitHub\CD-Luciana

In [6]:
dados = pd.read_csv('DOM2009.csv', sep=',')
dados_resumidos = dados.loc[ : ,['V4623','V4105','V0202','V0211','V4622']]
dados_resumidos.to_csv('resumo.csv')
dados_resumidos

        V4623  V4105  V0202  V0211  V4622
0         NaN      1    NaN    NaN    NaN
1         NaN      1    NaN    NaN    NaN
2         3.0      1    2.0    1.0    2.0
3         6.0      1    2.0    1.0    5.0
4         6.0      1    2.0    1.0    4.0
5         NaN      1    NaN    NaN    NaN
6         1.0      1    2.0    1.0    2.0
7         1.0      1    2.0    1.0    3.0
8         3.0      1    2.0    1.0    1.0
9         7.0      1    2.0    1.0    7.0
10        3.0      1    2.0    1.0    1.0
11        NaN      1    NaN    NaN    NaN
12        1.0      1    2.0    1.0    3.0
13        1.0      1    2.0    1.0    0.0
14        7.0      1    2.0    1.0    4.0
15        1.0      1    2.0    1.0    3.0
16        1.0      1    2.0    1.0    1.0
17        NaN      1    NaN    NaN    NaN
18        1.0      1    2.0    1.0    2.0
19        4.0      1    2.0    3.0    1.0
20        NaN      1    NaN    NaN    NaN
21        1.0      1    2.0    1.0    3.0
22        6.0      1    2.0    1.0    6.0
23        1.0      1    2.0    1.0    1.0
24        1.0      1    2.0    1.0    2.0
25        8.0      1    2.0    1.0    4.0
26        1.0      1    2.0    1.0    5.0
27        9.0      1    2.0    1.0    2.0
28        NaN      1    NaN    NaN    NaN
29        2.0      1    2.0    1.0    1.0
...       ...    ...    ...    ...    ...
153807    1.0      1    4.0    1.0   99.0
153808    6.0      1    4.0    1.0    7.0
153809    1.0      1    4.0    1.0   99.0
153810    2.0      1    4.0    1.0    6.0
153811    1.0      2    4.0    1.0    7.0
153812    NaN      2    NaN    NaN    NaN
153813    NaN      2    NaN    NaN    NaN
153814    NaN      2    NaN    NaN    NaN
153815    6.0      2    4.0    1.0    7.0
153816    NaN      2    NaN    NaN    NaN
153817    1.0      2    4.0    1.0    7.0
153818    6.0      2    4.0    1.0    7.0
153819    1.0      2    4.0    1.0    7.0
153820    NaN      2    NaN    NaN    NaN
153821    NaN      2    NaN    NaN    NaN
153822    NaN      2    NaN    NaN    NaN
153823    1.0      2    4.0    1.0    7.0
153824    NaN      2    NaN    NaN    NaN
153825    NaN      2    NaN    NaN    NaN
153826    NaN      2    NaN    NaN    NaN
153827    NaN      2    NaN    NaN    NaN
153828    NaN      2    NaN    NaN    NaN
153829    NaN      2    NaN    NaN    NaN
153830    6.0      2    4.0    1.0    6.0
153831    6.0      2    4.0    1.0   99.0
153832    6.0      2    4.0    1.0    7.0
153833    NaN      2    NaN    NaN    NaN
153834    1.0      2    4.0    1.0    7.0
153835    1.0      2    4.0    1.0    7.0
153836    1.0      2    4.0    1.0    7.0

[153837 rows x 5 columns]

___
## Conclusão

Descreva aqui suas conclusões!